CREATE DATABASE F_ESPORTE;

USE F_ESPORTE;

CREATE TABLE `F_ESPORTE`.`tb_produto` (
  `id_Produto` BIGINT NOT NULL AUTO_INCREMENT,
  `Nr_Serie` VARCHAR(45) NOT NULL,
  `De_Produto` VARCHAR(100) NOT NULL,
  `VR_Custo` DECIMAL(7,2) NOT NULL,
  `VR_Venda` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_Produto`),
  UNIQUE INDEX `Nr_Serie_UNIQUE` (`Nr_Serie` ASC));

CREATE TABLE `F_ESPORTE`.`tb_cliente` (
  `id_Cliente` BIGINT NOT NULL AUTO_INCREMENT,
  `Nm_Cliente` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_Cliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC));
 
CREATE TABLE `F_ESPORTE`.`TB_Endereco`(
Id_Endereco BIGINT NOT NULL AUTO_INCREMENT,
De_Endereco VARCHAR(256) NOT NULL,
NU_Endereco INT(5),
NU_CEP VARCHAR(9) NOT NULL,
De_Bairro VARCHAR(100) NOT NULL,
De_Cidade VARCHAR(100) NOT NULL,
UF VARCHAR(2) NOT NULL,
PRIMARY KEY (Id_Endereco)
);

ALTER TABLE `F_ESPORTE`.`tb_endereco`
ADD COLUMN `Id_Cliente` BIGINT NOT NULL AFTER `UF`,
ADD INDEX `FK_CLIENTE_idx` (`Id_Cliente` ASC);

ALTER TABLE `F_ESPORTE`.`tb_endereco`
ADD CONSTRAINT `FK_CLIENTE_ENDERECO`
  FOREIGN KEY (`Id_Cliente`)
  REFERENCES `F_ESPORTE`.`tb_cliente` (`id_Cliente`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


CREATE TABLE `F_ESPORTE`.`TB_VENDA`(
ID_VENDA BIGINT NOT NULL AUTO_INCREMENT,
VR_TOTAL DECIMAL(7,2) NOT NULL,
ID_CLIENTE BIGINT NOT NULL,
PRIMARY KEY (ID_VENDA)
);

ALTER TABLE `F_ESPORTE`.`tb_VENDA`
ADD CONSTRAINT `FK_CLIENTE`
  FOREIGN KEY (`Id_Cliente`)
  REFERENCES `F_ESPORTE`.`tb_cliente` (`id_Cliente`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
 
CREATE TABLE `F_ESPORTE`.`TB_VENDA_PRODUTO`(
ID_VENDA BIGINT NOT NULL,
ID_PRODUTO BIGINT NOT NULL,
QTD_PRODUTO INT NOT NULL,
VR_PRODUTO DECIMAL(7,2) NOT NULL,
PRIMARY KEY (ID_VENDA, ID_PRODUTO)
);

ALTER TABLE `F_ESPORTE`.`tb_VENDA_PRODUTO`
ADD CONSTRAINT `FK_VENDA`
  FOREIGN KEY (`ID_VENDA`)
  REFERENCES `F_ESPORTE`.`tb_VENDA` (`id_VENDA`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
 
ALTER TABLE `F_ESPORTE`.`tb_VENDA_PRODUTO`
ADD CONSTRAINT `FK_PRODUTO`
  FOREIGN KEY (`Id_PRODUTO`)
  REFERENCES `F_ESPORTE`.`tb_PRODUTO` (`id_PRODUTO`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;